web:
  port: 32861
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeC
    password: nodeC
  rateLimiting:
    enabled: false
soulseek:
  username: nodeC
  password: nodeC
  listenPort: 40467
sharing:
  tokenSigningKey: 1BAB7NHU3Z5q72n8mjQuewf3gZUQJo1VzkcCIvbBebc=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-32861/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-32861/incomplete
shares:
  directories: []
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
