web:
  port: 33919
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeA
    password: nodeA
  rateLimiting:
    enabled: false
  cors:
    enabled: true
    allowCredentials: false
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
soulseek:
  username: nodeA
  password: nodeA
  listenPort: 39637
sharing:
  tokenSigningKey: 5NBay6CHRYexCu63GJRxebhfSo54uB0ljCsn6HB6oRs=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/A-33919/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/A-33919/incomplete
shares:
  directories:
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/movie
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/book
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
