web:
  port: 34389
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeC
    password: nodeC
  rateLimiting:
    enabled: false
soulseek:
  username: nodeC
  password: nodeC
  listenPort: 37413
sharing:
  tokenSigningKey: 7wolBK9HK32QvoFOUVz15Gl1ZsLW8+V9hm+IYyMAM2Y=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-34389/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-34389/incomplete
shares:
  directories: []
feature:
  identityFriends: true
  collectionsSharing: true
  streaming: true
  streamingRelayFallback: true
  meshParallelSearch: true
  meshPublishAvailability: true
  scenePodBridge: true
  swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
