web:
  port: 41769
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeB
    password: nodeB
  rateLimiting:
    enabled: false
soulseek:
  username: nodeB
  password: nodeB
  listenPort: 44609
sharing:
  tokenSigningKey: iaHlYH+lE9jGo77bcpzOWE0x8UOabK7ca6PlAxWTGg4=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-41769/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-41769/incomplete
shares:
  directories:
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/music
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/tv
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
