web:
  port: 34511
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeB
    password: nodeB
  rateLimiting:
    enabled: false
soulseek:
  username: nodeB
  password: nodeB
  listenPort: 39821
sharing:
  tokenSigningKey: ibZEroYDkPVokLxz2C1MBZDEwfNt2u6ryHgB2myKqn0=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-34511/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-34511/incomplete
shares:
  directories:
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/book
feature:
  identityFriends: true
  collectionsSharing: true
  streaming: true
  streamingRelayFallback: true
  meshParallelSearch: true
  meshPublishAvailability: true
  scenePodBridge: true
  swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
