web:
  port: 43769
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeA
    password: nodeA
  rateLimiting:
    enabled: false
soulseek:
  username: nodeA
  password: nodeA
  listenPort: 43685
sharing:
  tokenSigningKey: c/INILxlNyg312IPT86sRcQAkjZLJhk0llR3H61aKkw=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/A-43769/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/A-43769/incomplete
shares:
  directories:
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/movie
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/book
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
