web:
  port: 38109
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeC
    password: nodeC
  rateLimiting:
    enabled: false
  cors:
    enabled: true
    allowCredentials: false
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
soulseek:
  username: nodeC
  password: nodeC
  listenPort: 37799
sharing:
  tokenSigningKey: dI7P6/Ju3PlBG1y+BdupBJhsF0TSLxlZG9BluIjFJKg=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-38109/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-38109/incomplete
shares:
  directories: []
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
