web:
  port: 40735
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeB
    password: nodeB
  rateLimiting:
    enabled: false
soulseek:
  username: nodeB
  password: nodeB
  listenPort: 45535
sharing:
  tokenSigningKey: U7yyvsp9UrbCidJP2FfeIFYL30wMM3yLG3a/5wQjzL0=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-40735/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/B-40735/incomplete
shares:
  directories:
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/music
    - /home/keith/Documents/code/slskdn/test-data/slskdn-test-fixtures/tv
feature:
  identityFriends: true
  collectionsSharing: true
  streaming: true
  streamingRelayFallback: true
  meshParallelSearch: true
  meshPublishAvailability: true
  scenePodBridge: true
  swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
