apiVersion: v1
kind: Service
metadata:
  name: {{ include "slskdn.fullname" . }}
  labels:
    {{- include "slskdn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.https.enabled }}
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "slskdn.selectorLabels" . | nindent 4 }}
