web:
  port: 33725
  host: 127.0.0.1
  https:
    disabled: true
  authentication:
    username: nodeC
    password: nodeC
  rateLimiting:
    enabled: false
  cors:
    enabled: true
    allowCredentials: false
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
soulseek:
  username: nodeC
  password: nodeC
  listenPort: 45691
sharing:
  tokenSigningKey: sCcILezvtDi1PEDHi8I3gO5kvC88DWG9WxT+igqBAqo=
directories:
  downloads: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-33725/downloads
  incomplete: /home/keith/Documents/code/slskdn/test-artifacts/e2e/C-33725/incomplete
shares:
  directories: []
feature:
  IdentityFriends: true
  CollectionsSharing: true
  Streaming: true
  StreamingRelayFallback: true
  MeshParallelSearch: true
  MeshPublishAvailability: true
  ScenePodBridge: true
  Swagger: true
overlay:
  enable: false
overlayData:
  enable: false
mesh:
  enableDht: false
  enableStun: false
  stunServers: []
  peerDescriptorRefresh:
    enableIpChangeDetection: false
flags:
  no_connect: true
